envelope: 9999
egresses:
  foo: http://localhost:8001/file.txt
  bar: http://localhost:8002/file.txt
  baz:
    mountebank:
      name: origin
      protocol: http
      stubs:
        - responses:
            - inject: |
                class State {
                  constructor()
                }
                (config) => {
                  config.logger.info('origin called');
                  config.state.requests = (config.state.requests || 0) + 1;
                  return {
                    headers: {
                      'Content-Type': 'application/json',
                    },
                    body: JSON.stringify({
                      count: config.state.requests,
                    }),
                  };
                }
